Repository petpple/sitter, pull requests merged in 2023-01, with the labels that each got.

#5 ⚡️ :: (#4) 파일 이동 및 펫시터 일지 완성 -동현
  src/main/java/petpple/kiwi/sitter/controller/Sitter/SitterController.java
  src/main/java/petpple/kiwi/sitter/controller/Vsitter/VSitterController.java
  src/main/resources/static/css/sitter/petMain.css
  src/main/resources/static/css/sitter/rSlider.min.css
  src/main/resources/static/css/sitter/sitterCal.css
  src/main/resources/static/css/sitter/sitterDiary.css
  src/main/resources/static/css/sitter/sitterMain.css
  src/main/resources/static/images/sitter/IMG_2087-scaled-e1634883900174.jpg
  src/main/resources/static/images/sitter/no_img.png
  src/main/resources/static/images/vsitter/calendar.svg
  src/main/resources/static/images/vsitter/diary.svg
  src/main/resources/static/images/vsitter/money.svg
  src/main/resources/static/images/vsitter/pet_info.svg
  src/main/resources/static/images/vsitter/profile.png
  src/main/resources/static/images/vsitter/sitting_on.svg
  src/main/resources/static/images/vsitter/timer-icon.svg
  src/main/resources/static/images/vsitter/u_svc.svg
  src/main/resources/static/images/vsitter/visit_svc.svg
  src/main/resources/static/javascript/sitter/rSlider.min.js
  src/main/webapp/WEB-INF/views/sitter/footer.jsp
  src/main/webapp/WEB-INF/views/sitter/sample.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterCal.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryForm.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryPetChoice.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryWritten.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterMain.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: 기능 추가

#7 📑 :: (#3) fistter 이사 - 영관
  src/main/java/petpple/kiwi/sitter/controller/Fsitter/FSitterController.java
  src/main/resources/static/css/fsitter/fsitterMyBlock.css
  src/main/resources/static/css/fsitter/fsitterMyInfo.css
  src/main/resources/static/css/fsitter/fsitterMyPet.css
  src/main/resources/static/css/fsitter/fsitterMyPetInsert.css
  src/main/resources/static/css/fsitter/fsitterMyProfile.css
  src/main/resources/static/images/fsitter/1.svg
  src/main/resources/static/images/fsitter/2.svg
  src/main/resources/static/images/fsitter/h1.svg
  src/main/resources/static/images/fsitter/h2.svg
  src/main/resources/static/images/fsitter/h3.svg
  src/main/resources/static/images/fsitter/h4.svg
  src/main/resources/static/images/fsitter/logo.svg
  src/main/resources/static/images/fsitter/logo1.png
  src/main/resources/static/images/fsitter/p.svg
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyInfo.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPet.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPetInsert.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPetUpdate.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyProfileUpdate.jsp
  src/main/webapp/WEB-INF/views/fsitter/header.jsp
Labels: 기능 추가

#9 ⚡️ :: (#6) 펫시터 정보 페이지 생성- 동현
  src/main/java/petpple/kiwi/sitter/controller/Sitter/SitterController.java
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/sitter/sitterDiary.css
  src/main/resources/static/css/sitter/sitterInfo.css
  src/main/webapp/WEB-INF/views/sitter/header.jsp
  src/main/webapp/WEB-INF/views/sitter/sample.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryForm.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryWritten.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterInfoFsvcPast.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterInfoFsvcWaiting.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterInfoUsvcPast.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterInfoUsvcWaiting.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterInfoVsvcPast.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterInfoVsvcWaiting.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterMain.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: 기능 추가

#10 ⚡️ :: (#8) fsitter 내 프로필 수정 - 영관
  src/main/java/petpple/kiwi/sitter/controller/Fsitter/FSitterController.java
  src/main/resources/static/css/fsitter/fsitterMyProfile.css
  src/main/resources/static/css/fsitter/fsitterPetSitterList.css
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyInfo.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPetInsert.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPetUpdate.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyProfileUpdate.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterPetSitterList.jsp
  src/main/webapp/WEB-INF/views/fsitter/header.jsp
Labels: 기능 추가

#14 ⚡️ :: (#11) fsitter 내 프로필 변경 수정 - 영관
  src/main/java/petpple/kiwi/sitter/controller/Fsitter/FSitterController.java
  src/main/resources/static/css/fsitter/fsitterCal.css
  src/main/resources/static/css/fsitter/fsitterMyPet.css
  src/main/resources/static/css/fsitter/fsitterMyPetInsert.css
  src/main/resources/static/css/fsitter/fsitterMyProfile.css
  src/main/webapp/WEB-INF/views/fsitter/fsitterCal.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPetInsert.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPetUpdate.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyProfileUpdate.jsp
Labels: 기능 추가

#16 📑 :: (#15) sts gradle에 oracle, mybatis 추가 - 보영
  build.gradle
  src/main/java/petpple/kiwi/sitter/domain/Member.java
  src/main/java/petpple/kiwi/sitter/model/.gitkeep
  src/main/java/petpple/kiwi/sitter/repository/MemberMapper.java
  src/main/java/petpple/kiwi/sitter/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/mapper/.gitkeep
  src/main/resources/mybatis-mapper/MemberMapper.xml
Labels: 기능 추가, 프로젝트 설정

#23 📑 :: (#19) sitterLogin 생성(미완) - 보영
  src/main/java/petpple/kiwi/sitter/controller/Sitter/SitterController.java
  src/main/java/petpple/kiwi/sitter/controller/Sitter/SitterLoginController.java
  src/main/java/petpple/kiwi/sitter/domain/sitter/Sitter.java
  src/main/java/petpple/kiwi/sitter/repository/sitter/ISitterMapper.java
  src/main/java/petpple/kiwi/sitter/service/sitter/SitterService.java
  src/main/resources/mybatis-mapper/SitterMapper.xml
  src/main/resources/static/css/sitter/sMain.css
  src/main/resources/static/css/sitter/sitterLoginForm.css
  src/main/webapp/WEB-INF/views/fsitter/header.jsp
  src/main/webapp/WEB-INF/views/sitter/header.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterLogin.jsp
  src/main/webapp/WEB-INF/views/vsitter/header.jsp
Labels: 기능 추가

#25 📑 :: (#22) VsitterMain 화면 수정 - 소연
  src/main/java/petpple/kiwi/sitter/controller/Sitter/SitterController.java
  src/main/java/petpple/kiwi/sitter/controller/Sitter/SitterMainController.java
  src/main/java/petpple/kiwi/sitter/domain/Vsitter.java
  src/main/java/petpple/kiwi/sitter/repository/IVsitterMapper.java
  src/main/resources/mybatis-mapper/VsitterMapper.xml
  src/main/webapp/WEB-INF/views/sitter/sitterMain.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: chore, 기능 추가

#27 ⚡️ :: (#26) Controller 수정 및 header out.print 주석 - 소연
  src/main/java/petpple/kiwi/sitter/controller/Fsitter/FSitterController.java
  src/main/java/petpple/kiwi/sitter/controller/Sitter/SitterController.java
  src/main/java/petpple/kiwi/sitter/domain/Vsitter.java
  src/main/webapp/WEB-INF/views/fsitter/header.jsp
  src/main/webapp/WEB-INF/views/sitter/header.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryForm.jsp
  src/main/webapp/WEB-INF/views/vsitter/header.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: chore, 기능 추가
